basePath: /
host: localhost:8080
info:
  contact:
    email: me@ssyan.ru
    name: Developer
  description: API for OAuth using Go Fiber
  license:
    name: MIT
    url: https://github.com/ssyan-dev/go-fiber-oauth/blob/main/LICENSE
  title: Go Fiber OAuth
  version: "1.0"
paths:
  /auth:
    get:
      description: Hello world!
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Check status
      tags:
      - Auth
  /auth/github:
    get:
      description: Redirect to GitHub Auth
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: GitHub OAuth
      tags:
      - Auth
  /auth/github/callback:
    get:
      description: GitHub Auth Callback
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: GitHub Auth Callback
      tags:
      - Auth
swagger: "2.0"
